Generate Class#openapi_nullable methods
patch-technology/patch-ruby pull request #19
Opened 2021-01-08 11:03 UTC by biglovisa

### What

Fixes #5. Adding generated method `.openapi_nullable` to models

### Why

This method was removed ~9 months back and was breaking the `#to_hash` method on the models. 

### SDK Release Checklist

- [ ] Have you added an integration test for the changes?
- [x] Have you built the gem locally and made queries against it successfully?
- [x] Did you update the changelog?
- [x] Did you bump the package version?
- [ ] For breaking changes, did you plan for the release of the new SDK versions and deploy the API to production?

2021-01-11 16:34 UTC, bspellacy requested changes
This looks good - can we add a test for the methods that weren't working before to prevent this from happening again?

2021-01-12 17:08 UTC, bspellacy commented
Sorry - I should have been more clear! The specs you added look great, but it was my understanding that `#to_hash` and `#to_h` were broken and those are the methods we should test.

2021-01-13 14:25 UTC, biglovisa commented
Ah yes - makes more sense, thanks for clarifying! I took the opportunity to create some shared examples instead for the generated classes. Currently we only cover the `.openapi_nullable` and `#to_hash` methods, but this can be added on to over time.

2021-01-13 16:42 UTC, bspellacy approved these changes

2021-01-13 17:11 UTC, merged